services:
  postgres-db:
    image: postgres:15
    container_name: aliassist-postgres
    restart: always
    environment:
      POSTGRES_USER: aliassist_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: aliassist_db
    ports:
      - "5432:5432"
    networks:
      - aliassist-network

  aliassistapp:
    container_name: aliassist-app
    build:
      context: .
      dockerfile: AliAssistApp/Dockerfile
    image: aliassistapp
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "5000:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Database=aliassist_db;Username=aliassist_user;Password=strongpassword"
    networks:
      - aliassist-network

networks:
  aliassist-network:
    driver: bridge